
# Global Game Configurations
SCREEN_SIZE = (400, 711)
DESIRED_FPS = 60
DESIRED_FRAME_INTERVAL = 1 / DESIRED_FPS
SHOW_FPS = False

BIRD_GRAVITY = 0.6
BIRD_JUMP_STRENGTH = 8
BIRD_TERMINAL_VELOCITY = 15
BIRD_LEFT_OFFSET = 50

PIPE_DISTANCE = 200
PIPE_SPEED = 2
PIPE_GAP = 180
PIPE_DIFFERENCE = 150
PIPE_MOVING_VERT_SPPED = 1

MOVING_PIPE_MIN_SCORE = 5
MOVING_PIPE_CHANCE = 0.5
